language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - PYTHONPATH='.'
install:
  - pip install -r requirements-test.txt -q --use-mirrors
  - npm install coffee-script wrench less
script:
  - cake all
  - django-admin.py test profiles books --settings="ook.development"