language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=ook.development
install:
  - pip install -r requirements-test.txt --use-mirrors
script:
  - echo $PYTHONPATH
  - django-admin.py test profiles books